---
title: "Receiver Performance Report"
author: 'FathomR'
date: "2024-11-09"
output: 
  html_document:
    self_contained: false
params: 
  data_list: NULL
  #variables: NULL
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
data_list <- params$data_list
#variables <- params$variables
```


## Receiver Configuration Report

### Receiver configuration
```{r receiver metadata summary, include=TRUE, echo=FALSE, warning=FALSE, message=FALSE}

receiver.meta <- cfg_channel %>%
  select(Serial, Model, `Map ID`) %>%
  left_join(event_init %>% select(Serial, `Firmware Version`))


receiver.meta %>% 
  kableExtra::kbl() %>% 
  kableExtra::kable_styling()
```

## Receiver Transmitter Specification
```{r include=TRUE, echo=FALSE, results='asis' }
receiver.config.meta <- cfg_channel %>% 
  select(Serial, Model, `Map ID`) %>% 
  left_join(cfg_transmitter %>% select(Serial, Time, `Full ID`, `Power Level`, `Min Delay (s)`, `Max Delay (s)`), by = c('Serial'))
  

# Get unique serial numbers
serial_numbers <- unique(receiver.config.meta$Serial)

#serial_numbers <- 0


for (i in serial_numbers){
  #serial_numbers <- serial_numbers + 1
  cat("\n# Receiver", i, '{.tabset}', "\n")
  cat("\n")
  
  df_subset <- subset(receiver.config.meta, Serial == serial_numbers[i])
  
  df_subset %>% 
  kableExtra::kbl() %>%
  kableExtra::kable_styling()
  cat("\n")
}

# 
# # Start of tab navigation HTML
# cat('<ul class="nav nav-tabs" role="tablist">')
# for (i in seq_along(serial_numbers)) {
#   # Create a tab for each serial number
#   tab_id <- paste0("tab_", i)
#   cat(sprintf('<li role="presentation" %s><a href="#%s" role="tab" data-toggle="tab">%s</a></li>',
#               if (i == 1) 'class="active"' else '',  # Set the first tab as active
#               tab_id,
#               serial_numbers[i]))
# }
# cat('</ul>')
# 
# # Start of tab content panels
# cat('<div class="tab-content">')
# for (i in seq_along(serial_numbers)) {
#   tab_id <- paste0("tab_", i)
#   
#   # Set the first panel as active
#   cat(sprintf('<div role="tabpanel" class="tab-pane %s" id="%s">', 
#               if (i == 1) 'active' else '', tab_id))
#   
#   # Filter data for the current serial number
#   df_subset <- subset(receiver.config.meta, Serial == serial_numbers[i])
#   
#   # Generate the content for each tab
#   cat(sprintf("<h3>Receiver Serial Number: %s</h3>", serial_numbers[i]))
#   
#   # Display summary statistics
#   cat("<h4>Summary Statistics</h4>")
#   df_subset %>% 
#   kableExtra::kbl() %>% 
#   kableExtra::kable_styling()
#   
#   # Create plots for numeric variables (optional)
#   # numeric_vars <- names(df_subset)[sapply(df_subset, is.numeric)]
#   # for (var in numeric_vars) {
#   #   cat(sprintf("<h5>Plot of %s</h5>", var))
#   #   print(plot(df_subset[[var]], main = paste("Plot of", var, "for Serial Number", serial_numbers[i])))
#   #}
#   
#   cat("</div>")  # Close the tab pane
# }
# 
# cat('</div>')  # Close the tab content


```



```{r receiver config, include=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
receiver.config.meta <- cfg_channel %>% 
  select(Serial, Model, `Map ID`) %>% 
  left_join(cfg_transmitter %>% select(Serial, Time, `Full ID`, `Power Level`, `Min Delay (s)`, `Max Delay (s)`), by = c('Serial'))
  

receiver.config.meta %>% 
  kableExtra::kbl() %>% 
  kableExtra::kable_styling()
```

## Receiver Clock Drift
```{r receiver clock ref, include=TRUE, echo=FALSE, warning=FALSE, message=FALSE}

receiver.clock_ref <- clock_ref %>% 
  filter(Source == 'OFFLOAD') %>% 
  select(Serial, `Device Time (UTC)`, `External Time (UTC)`, `External Difference (s)`, Source)

receiver.clock_ref %>% 
  kableExtra::kbl() %>% 
  kableExtra::kable_styling()
```

## Receiver Issues
```{r receiver firmware events, include=TRUE, echo=FALSE, message=FALSE, warning=FALSE}
rec.events <- event %>%
  select(Serial, `Device Time (UTC)`, Type, Description)

rec.events %>% 
  kableExtra::kbl() %>% 
  kableExtra::kable_styling()
```

## Receiver Offload
```{r receiver offload, include=TRUE, echo=FALSE, warning=FALSE, message=FALSE}
event_offload %>% 
  select(Serial, `Device Time (UTC)`, `External Time (UTC)`, `External Time Zone`, `PPM Total Accepted Detections`,
         `Battery Remaining (%)`, `Memory Remaining (%)`) %>% 
  kableExtra::kbl() %>% 
  kableExtra::kable_styling()

```

## Detection Summaries

### Internal Transmitter Detection Summary
```{r dets, include=TRUE, echo=FALSE, warning=FALSE, error=FALSE, message=FALSE}

internal_Tx <- receiver.config.meta$`Full ID`

int.Tx.dets <- det %>% 
  filter(`Full ID` %in% internal_Tx)

animal.dets <- det %>% 
  filter(!`Full ID` %in% internal_Tx)

int.Tx.dets %>% 
  group_by(Serial, `Full ID`) %>% 
  summarise(count = n()) %>% 
  kableExtra::kbl() %>% 
  kableExtra::kable_styling()

ggplot(int.Tx.dets)+
  geom_bar(aes(as.factor(Serial)))+
  labs(x = 'Serial', y='Detection Count', title ='Internal Transmitter Detection Count')

```

### Animal Detection Summary
```{r animal det summary, include=TRUE, echo=FALSE, warning=FALSE, error=FALSE}

animal.dets %>% 
  group_by(Serial) %>% 
  summarise(count = n()) %>% 
  kableExtra::kbl() %>% 
  kableExtra::kable_styling()


ggplot(animal.dets)+
  geom_bar(aes(y = as.factor(Serial)))+
  labs(x = 'Serial', y='Detection Count', title ='Internal Transmitter Detection Count')

ggplot(animal.dets)+
  geom_bar(aes(y=as.factor(`Full ID`)))+
  labs(y='Detection Count', title = 'Animal Detection Count')



```
