#' Fathom to VUE
#'
#' Helper function to convert detection data parsed by parse_fathom_files() to replicate the data structure of detections exported from legacy Vemco User Environment (VUE) software.
#'
#'
#' @param det tibble containing detection data generated by parse_fathom_files()
#'
#' @param cfg_station tibble containing station configuration data generated by parse_fathom_files()
#'
#' @param spec_sheet tibble containing transmitter specification generated using glatos::read_vemco_tag_specs()
#'
#' @return Returns a tibble containing data formatted to match the strucuture of detection data exported from VUE software
#' Tibble also contains a 'Time.corrected' variable which in the Date.and.Time..UTC. following lineaer time correction to
#' compensate for receiver clock drift
#'
#' @examples
#'
#' \dontrun{
#' #'   # This example shows how to call the process_log_files function
#' #'   # Replace "/path/to/your/data" with a valid directory path on your system
#' #'   parse_fathom_files('/path_to_fathom_csv_files', rec_type = c("DET, "CFG_STATION"), output = 'env")
#'
#' #'   # without  transmitter spec_sheet
#' #'   x <- fathom_to_vue_conversion(det, cfg_station)
#'
#' #'   # with transmitter spec_sheet
#'
#' #' spec_files <- list.files('path/to/spec_sheet', pattern='.xls', full.names = TRUE)

#' #'     spec_sheet <- lapply(spec_files, read_vemco_tag_specs) %>%
#' #'     map_dfr(~as_tibble(.x$specs)) %>%
#' #'     mutate(Transmitter = paste0(code_space,'-',id_code))
#' #'   x <- fathom_to_vue_conversion(det, cfg_station, spec_sheet = spec_sheet)
#'

#' #' }
#'
#'
#' @export fathom_to_vue
#'


fathom_to_vue <- function(det, cfg_station, spec_sheet = NULL) {

  det_red <- det %>%
    dplyr::select(
      `Device Time (UTC)`, Time, Model, Serial, `Full ID`,
      `Transmitter Serial`, `Raw Data`, `Station Name`, Latitude, Longitude
    ) %>%
    dplyr::mutate(
      Transmitter.Name     = "",
      Sensor.Unit          = "",
      `Transmitter Serial` = "",
      Transmitter.Type     = "",
      Sensor.Precision     = "",
      Receiver             = paste0(stringr::str_extract(Model, "^[^-]+"), "-", Serial)
    ) %>%
    dplyr::rename(
      Date.and.Time..UTC. = `Device Time (UTC)`,
      Transmitter            = `Full ID`,
      Transmitter.Serial     = `Transmitter Serial`,
      Sensor.Value           = `Raw Data`,
      Station.Name           = `Station Name`
    )

  # Station join only if cfg_station has rows
  if (is.data.frame(cfg_station) && nrow(cfg_station) > 0) {

    det_red <- det_red %>%
      dplyr::left_join(
        cfg_station %>%
          dplyr::select(Serial, `Station Name`, `Latitude (deg)`, `Longitude (deg)`),
        by = "Serial"
      ) %>%
      dplyr::mutate(
        Latitude     = `Latitude (deg)`,
        Longitude    = `Longitude (deg)`,
        Station.Name = `Station Name`
      ) %>%
      dplyr::select(-`Latitude (deg)`, -`Longitude (deg)`, -`Station Name`)

  } else {
    # Ensure columns exist (keep whatever det had; just standardise types)
    det_red <- det_red %>%
      dplyr::mutate(
        Latitude     = suppressWarnings(as.numeric(Latitude)),
        Longitude    = suppressWarnings(as.numeric(Longitude)),
        Station.Name = as.character(Station.Name)
      )
  }

  det_red <- det_red %>%
    dplyr::select(
      Date.and.Time..UTC., Time, Receiver, Transmitter, Transmitter.Name, Transmitter.Serial,
      Sensor.Value, Sensor.Unit, Station.Name, Latitude, Longitude, Transmitter.Type, Sensor.Precision
    )

  # Optional enrichment branch
  if (!is.null(spec_sheet)) {

    det_red <- det_red %>%
      dplyr::left_join(
        spec_sheet %>%
          dplyr::select(Transmitter, serial_number, sensor_units, sensor_slope, sensor_intercept),
        by = "Transmitter"
      ) %>%
      dplyr::mutate(
        Sensor.Unit = dplyr::case_when(
          Sensor.Value == "" ~ Sensor.Unit,
          Sensor.Value != "" & !is.na(sensor_units) ~ sensor_units,
          Sensor.Value != "" &  is.na(sensor_units) ~ "ADC",
          TRUE ~ Sensor.Unit
        ),
        Transmitter.Serial = dplyr::coalesce(serial_number, Transmitter.Serial),
        Sensor.Value = dplyr::if_else(
          Sensor.Value != "" &
            !is.na(Sensor.Unit) &
            !is.na(sensor_slope) &
            !is.na(sensor_intercept),
          as.character(as.numeric(Sensor.Value) * sensor_slope + sensor_intercept),
          Sensor.Value
        )
      ) %>%
      dplyr::select(-serial_number, -sensor_units, -sensor_slope, -sensor_intercept)

  } else {

    det_red <- det_red %>%
      dplyr::mutate(Sensor.Unit = dplyr::if_else(Sensor.Value != "", "ADC", Sensor.Unit))
  }

  det_red %>%
    dplyr::arrange(Time) %>%
    dplyr::rename(Time.corrected = Time) %>%
    dplyr::mutate(dplyr::across(where(is.character), ~ dplyr::na_if(.x, "")))
}
